### PR TITLE
feat: add checksum in kpm workflow

### LINKED ISSUE #394: [LFT Term 3]: The checksum check of the three-party dependencies
## Enhancement

The checksum verification of the dependencies in `kpm` has not been completed, and this part needs to be redesigned and completed.

#### A paper work
- A technical proposal for common package management tools checksum checking such as cargo, npm, go. mainly includes:
- - The main purpose of checking checksum
- - Related to the checksum check function
- - To implement the checksum check, which parts need to finished
- - Combined with kpm, which functions of kpm need to add checksum
- - For the existing kpm dependencies, we need a solution that does not break compatibility for starting this feature

### PR DESCRIPTION
**Pull request by NishantBansal2003**
#### 1. Does this PR affect any open issues?(Y/N) and add issue references:
fix #394 
- [ ] N
- [x] Y 

#### 2. What is the scope of this PR (e.g. component or file name):
pkg/client/client.go

#### 3. Provide a description of the PR(e.g. more details, effects, motivations or doc link):
This PR adds a checksum verification step to the `kpm` workflow to enhance the security and integrity of third-party dependencies. The integration ensures that each package’s checksum is validated during downloading, preventing unauthorized or tampered packages from being incorporated into the project.

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [x] Contains experimental features
- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Other

#### 4. Are there any breaking changes?(Y/N) and describe the breaking changes(e.g. more details, motivations or doc link):

- [x] N
- [ ] Y 

#### 5. Are there test cases for these changes?(Y/N) select and add more details, references or doc links:

- [x] Unit test
- [ ] Integration test
- [ ] Benchmark (add benchmark stats below)
- [ ] Manual test (add detailed scripts or steps below)
- [ ] Other

### CODE REVIEW

**Comment by NishantBansal2003** [comment]
Will fix the failing CI after this PR (https://github.com/kcl-lang/modules/pull/243) is merged and I have received reviews on the current checksum integration code design.

**Comment by NishantBansal2003** [comment]
> 😄 I will update it later in this PR https://github.com/kcl-lang/kpm/pull/520

cc: @zong-zhe

**Comment by zong-zhe** [comment]
Hi @NishantBansal2003 😄 

I have tried to test your PR locally, And I think that it needs a feature flag to control the checksum function on and off, because checksum function is a destructive function, it may cause the user's client to not work properly, which is probably the main reason why tests fail in Github Action. You can refer to some of the feature flags implemented here https://github.com/kcl-lang/kpm/blob/63bea3a98e47eb531480be6f8b3a21f664582a93/pkg/features/features.go#L13, and add a switch to the functionality of your PR.

**Review by zong-zhe — APPROVED** [review]
LGTM

**Pull request merged**
