### PR TITLE
design of selection strategy

### PR DESCRIPTION
**Pull request by AkashKumar7902**
#### 1. Does this PR affect any open issues?(Y/N) and add issue references (e.g. "fix #123", "re #123".):

- [ ] N
- [x] Y 

fix: #269 

#### 3. Provide a description of the PR(e.g. more details, effects, motivations or doc link):

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Other

#### 4. Are there any breaking changes?(Y/N) and describe the breaking changes(e.g. more details, motivations or doc link):

- [ ] N
- [ ] Y 

#### 5. Are there test cases for these changes?(Y/N) select and add more details, references or doc links:

- [ ] Unit test
- [ ] Integration test
- [ ] Benchmark (add benchmark stats below)
- [ ] Manual test (add detailed scripts or steps below)
- [ ] Other

### CODE REVIEW

**Comment by Peefy** [comment]
I think this design LGTM. Can you sign the DCO? We may merge at an appropriate time.

Besides, @zong-zhe, do you have any more suggestions and additions?

**Comment by zong-zhe** [comment]
@AkashKumar7902 😄

LGTM, maybe you need to squash commits into one and sign the DCO with the one commit.

**Comment by AkashKumar7902** [comment]
@zong-zhe done!

**Review by Peefy — APPROVED** [review]
LGTM

**Pull request merged**
