### PR TITLE
[PreTest]The checksum check of the three-party dependencies 

### LINKED ISSUE #394: [LFT Term 3]: The checksum check of the three-party dependencies
## Enhancement

The checksum verification of the dependencies in `kpm` has not been completed, and this part needs to be redesigned and completed.

#### A paper work
- A technical proposal for common package management tools checksum checking such as cargo, npm, go. mainly includes:
- - The main purpose of checking checksum
- - Related to the checksum check function
- - To implement the checksum check, which parts need to finished
- - Combined with kpm, which functions of kpm need to add checksum
- - For the existing kpm dependencies, we need a solution that does not break compatibility for starting this feature

### PR DESCRIPTION
**Pull request by vinayakjaas**
#### 1. Does this PR affect any open issues?(Y/N) and add issue references (e.g. "fix #394 ",.):

- [ ] N
- [x] Y 

#### 3. Provide a description of the PR(e.g. more details, effects, motivations or doc link):

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [x] Other

#### 4. Are there any breaking changes?(Y/N) and describe the breaking changes(e.g. more details, motivations or doc link):

- [x] N
- [ ] Y 

#### 5. Are there test cases for these changes?(Y/N) select and add more details, references or doc links:

- [ ] Unit test
- [ ] Integration test
- [ ] Benchmark (add benchmark stats below)
- [ ] Manual test (add detailed scripts or steps below)
- [ ] Other

### CODE REVIEW

**Comment by vinayakjaas** [comment]
Hey @Peefy ,@zong-zhe,@AkashKumar7902 I've opened a pull request that includes detailed documentation regarding the checksum check for third-party dependencies. I've put significant effort into designing this, but I would greatly appreciate your review and any necessary modifications.
Please note that the implementation may not be complete yet, as I am still exploring codebase to find some additional approaches to address the issue. I’m happy to make further changes based on your feedback.

**Comment by zong-zhe** [comment]
Hi @vinayakjaas 😃

Split the different jobs into their own PR and associate them with the corresponding issues.

**Comment by vinayakjaas** [comment]
Hey @zong-zhe, I have separated both pull requests as requested. Could you please go through and review them

**Comment by vinayakjaas** [comment]
Hi  @zong-zhe ,  please review this PR If you find any modifications are needed, please let me know, and I'll be happy to make the necessary changes.

**Comment by zong-zhe** [comment]
Hi @vinayakjaas 😄 

Try to add a separate module `Checker` to complete this part of the work, including three-party dependency name check, version number check and sum check.

**Pull request closed without merging**
