### PR TITLE
Added contribution guideline link in README

### LINKED ISSUE #247: Add Contributing.md
## Feature Request

**Is your feature request related to a problem? Please describe:**

I came to this repo and wanted to learn how to contribute to it but I could not find any contributing.md file

**Describe the feature you'd like:**

A CONTRIBUTING.md file is a document within a software project repository that provides guidelines and information for individuals who want to contribute to the project. This file serves as a reference for potential contributors, helping them understand the project's development process, expectations, and how they can effectively participate. Below is an example template for a CONTRIBUTING.md file.

I would like to work on this issue.

### PR DESCRIPTION
**Pull request by atarax665**
#### 1. Does this PR affect any open issues?(Y/N) and add issue references (e.g. "fix #123", "re #123".):

- [ ] N
- [x] Y 
Fix #247 

#### 2. What is the scope of this PR (e.g. component or file name):

README.md
#### 3. Provide a description of the PR(e.g. more details, effects, motivations or doc link):

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [x] Other

#### 4. Are there any breaking changes?(Y/N) and describe the breaking changes(e.g. more details, motivations or doc link):

- [x] N
- [ ] Y 

#### 5. Are there test cases for these changes?(Y/N) select and add more details, references or doc links:

- [ ] Unit test
- [ ] Integration test
- [ ] Benchmark (add benchmark stats below)
- [ ] Manual test (add detailed scripts or steps below)
- [ ] Other

### CODE REVIEW

**Comment by atarax665** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Peefy** [comment]
> I have read the CLA Document and I hereby sign the CLA

Hello @atarax665, thank your for contribution! Pls sign the DCO.

**Comment by zong-zhe** [comment]
Hi @atarax665 😊

Thanks for your contribution 👍. You can adjust your commit message using `git commit --amend -s`

More details - https://github.com/apps/dco

**Comment by zong-zhe** [comment]
Hi @atarax665 😄
Thanks for your contribution. You need to sign the DCO by `git commit -s`, signing this document not only protects your rights, but also ensures our cooperation is smoother and more transparent

**Pull request merged**
